"""Metaluminous prompts package"""
from .templates import (
    GENERATION_PROMPT,
    CRITIQUE_PROMPT,
    LOGIC_CHECK_PROMPT,
    CONTRADICTION_FINDER_PROMPT,
    NOVELTY_ASSESSMENT_PROMPT,
    EDGE_CASE_GENERATOR_PROMPT,
    CONSENSUS_SYNTHESIS_PROMPT,
    METALUMINOSITY_FRAMEWORK,
    MEASUREMENT_CONSCIOUSNESS_TEMPLATE,
    FORMAL_ETHICS_TEMPLATE,
    CONSCIOUSNESS_TOPOLOGY_TEMPLATE,
    CONTRADICTION_MINING_TEMPLATE,
)

__all__ = [
    "GENERATION_PROMPT",
    "CRITIQUE_PROMPT",
    "LOGIC_CHECK_PROMPT",
    "CONTRADICTION_FINDER_PROMPT",
    "NOVELTY_ASSESSMENT_PROMPT",
    "EDGE_CASE_GENERATOR_PROMPT",
    "CONSENSUS_SYNTHESIS_PROMPT",
    "METALUMINOSITY_FRAMEWORK",
    "MEASUREMENT_CONSCIOUSNESS_TEMPLATE",
    "FORMAL_ETHICS_TEMPLATE",
    "CONSCIOUSNESS_TOPOLOGY_TEMPLATE",
    "CONTRADICTION_MINING_TEMPLATE",
]
